[package]
name = "advent"
version = "0.1.0"
authors = ["Colin Gilgenbach <colin@gilgenbach.net>"]
edition = "2021"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"
ndarray = "0.16.1"
ndarray-conv = "0.5.2"
petgraph = "0.8.3"
